// In a real-world application, this list might be fetched from a backend API
// or a more robust static data source. This is a representative, expanded list.
export const largeIndianColleges: string[] = [
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "Indian Institute of Technology Varanasi (BHU)",
  "Indian Institute of Technology Indore",
  "Indian Institute of Technology (ISM) Dhanbad",
  "Indian Institute of Technology Gandhinagar",
  "Indian Institute of Technology Ropar",
  "Indian Institute of Technology Bhubaneswar",
  "Indian Institute of Technology Mandi",
  "Indian Institute of Technology Jodhpur",
  "Indian Institute of Technology Patna",
  "Indian Institute of Technology Tirupati",
  "Indian Institute of Technology Palakkad",
  "Indian Institute of Technology Bhilai",
  "Indian Institute of Technology Goa",
  "Indian Institute of Technology Jammu",
  "Indian Institute of Technology Dharwad",
  "National Institute of Technology Tiruchirappalli",
  "National Institute of Technology Karnataka, Surathkal",
  "National Institute of Technology Rourkela",
  "National Institute of Technology Warangal",
  "National Institute of Technology Calicut",
  "National Institute of Technology Nagpur",
  "National Institute of Technology Durgapur",
  "National Institute of Technology Kurukshetra",
  "National Institute of Technology Silchar",
  "National Institute of Technology Jaipur",
  "National Institute of Technology Delhi",
  "National Institute of Technology Jalandhar",
  "National Institute of Technology Bhopal",
  "National Institute of Technology Agartala",
  "National Institute of Technology Goa",
  "National Institute of Technology Hamirpur",
  "National Institute of Technology Jamshedpur",
  "National Institute of Technology Manipur",
  "National Institute of Technology Meghalaya",
  "National Institute of Technology Mizoram",
  "National Institute of Technology Nagaland",
  "National Institute of Technology Puducherry",
  "National Institute of Technology Sikkim",
  "National Institute of Technology Srinagar",
  "National Institute of Technology Uttarakhand",
  "National Institute of Technology Andhra Pradesh",
  "Anna University, Chennai",
  "Vellore Institute of Technology (VIT)",
  "SRM Institute of Science and Technology",
  "Manipal Academy of Higher Education",
  "Amrita Vishwa Vidyapeetham",
  "Birla Institute of Technology & Science (BITS) Pilani",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Jamia Millia Islamia, New Delhi",
  "Aligarh Muslim University",
  "University of Delhi",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "University of Hyderabad",
  "Osmania University, Hyderabad",
  "Mumbai University",
  "Pune University",
  "Bangalore University",
  "Jadavpur University, Kolkata",
  "Presidency University, Kolkata",
  "Indian Institute of Science (IISc) Bangalore",
  "All India Institute of Medical Sciences (AIIMS) Delhi",
  "Christian Medical College (CMC) Vellore",
  "Armed Forces Medical College (AFMC) Pune",
  "Maulana Azad Medical College (MAMC) Delhi",
  "King George's Medical University (KGMU) Lucknow",
  "Grant Medical College, Mumbai",
  "Seth GS Medical College, Mumbai",
  "Madras Medical College, Chennai",
  "St. John's Medical College, Bangalore",
  "Lady Hardinge Medical College, New Delhi",
  "Institute of Medical Sciences, BHU",
  "Postgraduate Institute of Medical Education and Research (PGIMER) Chandigarh",
  "National Institute of Mental Health and Neurosciences (NIMHANS) Bangalore",
  "Indian Institute of Management Ahmedabad",
  "Indian Institute of Management Bangalore",
  "Indian Institute of Management Calcutta",
  "Indian Institute of Management Lucknow",
  "Indian Institute of Management Kozhikode",
  "Indian Institute of Management Indore",
  "Indian Institute of Management Shillong",
  "Indian Institute of Management Udaipur",
  "Indian Institute of Management Ranchi",
  "Indian Institute of Management Rohtak",
  "" // Empty string for "Other" or custom input if needed, though combobox handles it
];